Added Ginger API key validation
gingerpayments/ginger-php pull request #11
Opened 2016-09-22 14:48 UTC by dmitrijev

2016-09-22 19:34 UTC, mgsander commented on src/Ginger.php
> +    public static function apiKeyToUuid($apiKey)
This function looks nasty... There must be a cleaner way to do this!

Maybe you can use the UUID lib at https://github.com/ramsey/uuid. Or else use a `preg_replace`?

```php
$uuid_hex = '663138387bca44eb9885b650d1f0026c';
$uuid = preg_replace('/(\w{8})(\w{4})(\w{4})(\w{4})(\w{12})/', '$1-$2-$3-$4-$5', $uuid_hex);
echo $uuid;
```

(From https://www.linkedin.com/pulse/20141204164718-2397294-convert-uuid-without-dashes-to-uuid-with-dashes?articleId=5946310918399873024)

2016-09-22 19:34 UTC, mgsander commented on tests/GingerTest.php
> +    public function itShouldCreateAValidUUD()
Typo: UUD -> UUID

Also, shouldn't it be `Uuid` instead, to be consistent with `apiKeyToUuid `?

2016-09-22 19:37 UTC, ghost requested changes

2016-09-23 08:45 UTC, dmitrijev commented
Indeed, using **preg_replace()** is a much more elegant solution!

2016-09-23 09:25 UTC, ghost approved these changes

2016-09-23 09:27 UTC, merged