Added locale to <customer> node in order creation request
gingerpayments/ginger-php pull request #14
Opened 2016-10-13 13:42 UTC by dmitrijev

2016-10-13 21:30 UTC, ghost approved these changes
Looks good in general.

2016-10-13 21:30 UTC, mgsander commented on src/Order/Customer/Locale.php
> +            Guard::regex($value, '/^[a-zA-Z]{2}(_[a-zA-Z]{2})?$/', "Locale : ".$value);
You could improve the validator regex a little, since the format is aa_BB. Maybe something like this: `/^[a-z]{2}(_[A-Z]{2})?$/`.

2016-10-13 21:30 UTC, mgsander commented on tests/Order/Customer/LocaleTest.php
> +        Locale::fromString('en_US');
I don't see what's wrong with this locale...

2016-10-13 21:30 UTC, mgsander commented on tests/Order/Customer/LocaleTest.php
> +            Locale::fromString('en_US')
Maybe also test the 'en' case? That should also work.

2016-10-14 07:24 UTC, dmitrijev commented
Thank you for constructive suggestions! Addressing them now.

2016-10-14 07:31 UTC, ghost requested changes

2016-10-14 07:31 UTC, mgsander commented on tests/Order/Customer/LocaleTest.php
> +        Locale::fromString('en');
I still don't understand why this passes the test. You'd think that 'en' is a valid locale, so the InvalidArgumentException should not be thrown. I think you need to split up this test into three separate ones.

2016-10-14 07:31 UTC, mgsander commented on tests/Order/Customer/LocaleTest.php
> +        Locale::fromString('en');
And since 'en' is valid, its test should look similar to `itShouldInstantiateFromAValidString`.

2016-10-14 07:35 UTC, dmitrijev commented on tests/Order/Customer/LocaleTest.php
> +        Locale::fromString('en');
you are right, _setExpectedException_ does not fail assertion if exception is not thrown.

2016-10-14 09:38 UTC, merged